### PR TITLE
REFS #26 and fixes #26(Day 11 task completed)

### PR DESCRIPTION
**Pull request by jevikraiyani12**

### CODE REVIEW

**Comment by jevikraiyani12** [comment]
Day13(blogen layout)

**Comment by jevikraiyani12** [comment]
Mizuxe layout completed(Day13)

**Comment by jevikraiyani12** [comment]
poject

**Comment by jevikraiyani12** [comment]
day14

**Comment by SharmaSachin27** [comment]
Day 9 --- [ card ,  media object  input  with Addons  Left  ]
Day 11       [  work is not proper  like navigation ] 
Screenshot (247)
   Day 14 onward remaining to commit

**Comment by jevikraiyani12** [comment]
Day15 done

**Comment by jevikraiyani12** [comment]
day15 changes

**Comment by jevikraiyani12** [comment]
Day 9 Day 11 changes done

**Comment by jevikraiyani12** [comment]
Day16 task Completed

**Comment by jevikraiyani12** [comment]
work done till Day20

**Comment by jevikraiyani12** [comment]
Till Day 24 done

**Pull request merged**
