### PR TITLE
REFS: #21 and fixes #21(Day 5 Task)

### PR DESCRIPTION
**Pull request by mitulsoni753**
REFS: #21 and fixes #21(Day 5 Task Complete)

### CODE REVIEW

**Review by radixdt12020 — CHANGES_REQUESTED** [review]
Day3 Task pattern validation not done

**Comment by mitulsoni753** [comment]
Day 3 Task Pattern Validation Completed

**Comment by mitulsoni753** [comment]
All File Updated

**Review by radixdt12020 — CHANGES_REQUESTED** [review]
Day8 grid layout not working. day14 nav bar not visible on mobile screen

**Review by radixdt12020 — APPROVED** [review]

**Review by radixdt12020 — CHANGES_REQUESTED** [review]

**Pull request merged**
