### PR TITLE
Successfully done.

### PR DESCRIPTION
**Pull request by Nisarg222**
REFS: #20 and fixes #20

### CODE REVIEW

**Comment by Nisarg222** [comment]
REFS: #20 and fixes #20

**Comment by Nisarg222** [comment]
Day5 work successfully done

**Comment by Nisarg222** [comment]
REFS: #23 and fixes #23
Day6 work done!.

**Review by radixdt12020 — CHANGES_REQUESTED** [review]
Day3 employee Form id should not be same for ename and eage.Day4 Assignment resume should be personlized not someone else, please rework on the same.Day5 Assignment images should be seperate folder

**Pull request closed without merging**
