### PR TITLE
REFS #20 and fixes #20 (Day 3 work is done)

### PR DESCRIPTION
**Pull request by vatsalpatel68**

### CODE REVIEW

**Comment by vatsalpatel68** [comment]
REFS #21 and fixes #21 (Day 4 task is done)

**Review by radixdt12020 — CHANGES_REQUESTED** [review]
Organiztional with nested list is remaing

**Review by radixdt12020 — CHANGES_REQUESTED** [review]
Day4 resume footer section is remaing

**Comment by vatsalpatel68** [comment]
Day4 footer inside resume is added . And make a nested list in Day3 practice

**Comment by vatsalpatel68** [comment]
REFS #22 and fixes #22 (Day 5 task is over)

**Comment by vatsalpatel68** [comment]
REFS #23 and fixes #23 (Day 6 tasks are done)

**Comment by vatsalpatel68** [comment]
REFS #23 and fixes #23 (Day 6 Extra work is Done)

**Comment by vatsalpatel68** [comment]
REFS #24 and fixes #24 ( Day 7 tasks are complete as well as make a website responsive)

**Comment by vatsalpatel68** [comment]
REFS #24 and fixes #24 (Done making of responsive website using grid)

**Pull request merged**
