### PR TITLE
REFS: rx-training#20 and fixes rx-training#20(commit day-3 tasks)

### PR DESCRIPTION
**Pull request by karansinghchauhan63**
REFS: rx-training#20 and fixes rx-training#20(commit day-3 tasks)

### CODE REVIEW

**Comment by karansinghchauhan63** [comment]
REFS:rx-training#20 and fixes rx-training#20 (correction done)

**Comment by karansinghchauhan63** [comment]
REFS:#21 and fixes #21 (commit tasks of day4)

**Comment by karansinghchauhan63** [comment]
REFS:rx-training#22 and fixes rx-training#22 (commit day5)

**Comment by DarshiL7** [comment]
[namara.docx](https://github.com/rx-training/Training-Jan-2021/files/5878469/namara.docx)
please rework on above file.

**Review by DarshiL7 — APPROVED** [review]
Screenshot (301)
selected line in not flexing.
please check and rework by resizing the browser.

**Pull request merged**
