### PR TITLE
REFS: #20 and fixes #20

### PR DESCRIPTION
**Pull request by charmi-tanna**
Day 4 task is completed

### CODE REVIEW

**Review by radixdt12020 — CHANGES_REQUESTED** [review]
Day3 Employee Registration form not required with javascript. you need to implement with required,pattern,email htm5. please redo that assignment Day4 assignmet apply proper margin and padding. Stylesheet should be there in seprate file.

**Review by radixdt12020 — CHANGES_REQUESTED** [review]
#20 Day3task.
image 
#21 Day4 Task 
image Day4 Assigment Resume class name should not be like a,b,c 
image Practice Exercise 2 and 4 not working.
#22 Day5 Assignment images folder not uploaded on git.
#24 Day6 practice exercise 5 and 6 not working
Day7 Practice exercise 3 element not on media size screen 600px;
Day8 class name should be meaningfull.
Day9 Task components are remaining

**Comment by DarshiL7** [comment]
image
 
Email Id field is pending in day3 Assignment task

**Comment by DarshiL7** [comment]
day4 Assignent rework, video 
day 6 practice 5 and 6 flex-container not working
day7 practice 3 not working
day8 grid is not working
day9 utilities drop-down links are not working

**Pull request merged**
